package com.entity;
// Generated 2016-12-28 20:12:31 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "ooad")
public class Employee implements java.io.Serializable {

	private Integer employeeId;
	private String employeeName;
	private Set<RecordBackup> recordBackups = new HashSet<RecordBackup>(0);
	private Set<RecordEquipment> recordEquipments = new HashSet<RecordEquipment>(0);

	public Employee() {
	}

	public Employee(String employeeName) {
		this.employeeName = employeeName;
	}

	public Employee(String employeeName, Set<RecordBackup> recordBackups, Set<RecordEquipment> recordEquipments) {
		this.employeeName = employeeName;
		this.recordBackups = recordBackups;
		this.recordEquipments = recordEquipments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "employeeID", unique = true, nullable = false)
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "employeeName", nullable = false)
	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<RecordBackup> getRecordBackups() {
		return this.recordBackups;
	}

	public void setRecordBackups(Set<RecordBackup> recordBackups) {
		this.recordBackups = recordBackups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<RecordEquipment> getRecordEquipments() {
		return this.recordEquipments;
	}

	public void setRecordEquipments(Set<RecordEquipment> recordEquipments) {
		this.recordEquipments = recordEquipments;
	}

}
