package com.entity;
// Generated 2016-12-28 20:12:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Equipment generated by hbm2java
 */
@Entity
@Table(name = "equipment", catalog = "ooad")
public class Equipment implements java.io.Serializable {

	private Integer equipmentId;
	private String quipmentName;
	private Date datePurchased;
	private Date dateDiscarded;
	private byte isBorrowed;
	private Set<RecordBackup> recordBackups = new HashSet<RecordBackup>(0);
	private Set<RecordEquipment> recordEquipments = new HashSet<RecordEquipment>(0);

	public Equipment() {
	}

	public Equipment(String quipmentName, Date datePurchased, byte isBorrowed) {
		this.quipmentName = quipmentName;
		this.datePurchased = datePurchased;
		this.isBorrowed = isBorrowed;
	}

	public Equipment(String quipmentName, Date datePurchased, Date dateDiscarded, byte isBorrowed,
			Set<RecordBackup> recordBackups, Set<RecordEquipment> recordEquipments) {
		this.quipmentName = quipmentName;
		this.datePurchased = datePurchased;
		this.dateDiscarded = dateDiscarded;
		this.isBorrowed = isBorrowed;
		this.recordBackups = recordBackups;
		this.recordEquipments = recordEquipments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "equipmentID", unique = true, nullable = false)
	public Integer getEquipmentId() {
		return this.equipmentId;
	}

	public void setEquipmentId(Integer equipmentId) {
		this.equipmentId = equipmentId;
	}

	@Column(name = "quipmentName", nullable = false)
	public String getQuipmentName() {
		return this.quipmentName;
	}

	public void setQuipmentName(String quipmentName) {
		this.quipmentName = quipmentName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datePurchased", nullable = false, length = 10)
	public Date getDatePurchased() {
		return this.datePurchased;
	}

	public void setDatePurchased(Date datePurchased) {
		this.datePurchased = datePurchased;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDiscarded", length = 10)
	public Date getDateDiscarded() {
		return this.dateDiscarded;
	}

	public void setDateDiscarded(Date dateDiscarded) {
		this.dateDiscarded = dateDiscarded;
	}

	@Column(name = "isBorrowed", nullable = false)
	public byte getIsBorrowed() {
		return this.isBorrowed;
	}

	public void setIsBorrowed(byte isBorrowed) {
		this.isBorrowed = isBorrowed;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipment")
	public Set<RecordBackup> getRecordBackups() {
		return this.recordBackups;
	}

	public void setRecordBackups(Set<RecordBackup> recordBackups) {
		this.recordBackups = recordBackups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipment")
	public Set<RecordEquipment> getRecordEquipments() {
		return this.recordEquipments;
	}

	public void setRecordEquipments(Set<RecordEquipment> recordEquipments) {
		this.recordEquipments = recordEquipments;
	}

}
