package com.entity;
// Generated 2016-12-28 22:04:42 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RecordEquipment generated by hbm2java
 */
@Entity
@Table(name = "recordEquipment", catalog = "ooad")
public class RecordEquipment implements java.io.Serializable {

	private int recordEquipmentId;
	private Employee employee;
	private Equipment equipment;
	private Date dateBorrowed;
	private Date dateReturned;

	public RecordEquipment() {
	}

	public RecordEquipment(int recordEquipmentId, Employee employee, Equipment equipment, Date dateBorrowed) {
		this.recordEquipmentId = recordEquipmentId;
		this.employee = employee;
		this.equipment = equipment;
		this.dateBorrowed = dateBorrowed;
	}

	public RecordEquipment(int recordEquipmentId, Employee employee, Equipment equipment, Date dateBorrowed,
			Date dateReturned) {
		this.recordEquipmentId = recordEquipmentId;
		this.employee = employee;
		this.equipment = equipment;
		this.dateBorrowed = dateBorrowed;
		this.dateReturned = dateReturned;
	}

	@Id

	@Column(name = "recordEquipmentID", unique = true, nullable = false)
	public int getRecordEquipmentId() {
		return this.recordEquipmentId;
	}

	public void setRecordEquipmentId(int recordEquipmentId) {
		this.recordEquipmentId = recordEquipmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employeeID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipmentID", nullable = false)
	public Equipment getEquipment() {
		return this.equipment;
	}

	public void setEquipment(Equipment equipment) {
		this.equipment = equipment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateBorrowed", nullable = false, length = 10)
	public Date getDateBorrowed() {
		return this.dateBorrowed;
	}

	public void setDateBorrowed(Date dateBorrowed) {
		this.dateBorrowed = dateBorrowed;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateReturned", length = 10)
	public Date getDateReturned() {
		return this.dateReturned;
	}

	public void setDateReturned(Date dateReturned) {
		this.dateReturned = dateReturned;
	}

}
