package com.entity;
// Generated 2016-12-28 20:12:31 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RecordBackup generated by hbm2java
 */
@Entity
@Table(name = "recordBackup", catalog = "ooad")
public class RecordBackup implements java.io.Serializable {

	private Integer recordBackupId;
	private Backup backup;
	private Employee employee;
	private Equipment equipment;
	private Date dateBorrowed;
	private Date dateReturned;

	public RecordBackup() {
	}

	public RecordBackup(Backup backup, Employee employee, Equipment equipment, Date dateBorrowed) {
		this.backup = backup;
		this.employee = employee;
		this.equipment = equipment;
		this.dateBorrowed = dateBorrowed;
	}

	public RecordBackup(Backup backup, Employee employee, Equipment equipment, Date dateBorrowed, Date dateReturned) {
		this.backup = backup;
		this.employee = employee;
		this.equipment = equipment;
		this.dateBorrowed = dateBorrowed;
		this.dateReturned = dateReturned;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recordBackupID", unique = true, nullable = false)
	public Integer getRecordBackupId() {
		return this.recordBackupId;
	}

	public void setRecordBackupId(Integer recordBackupId) {
		this.recordBackupId = recordBackupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "backupID", nullable = false)
	public Backup getBackup() {
		return this.backup;
	}

	public void setBackup(Backup backup) {
		this.backup = backup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employeeID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipmentID", nullable = false)
	public Equipment getEquipment() {
		return this.equipment;
	}

	public void setEquipment(Equipment equipment) {
		this.equipment = equipment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateBorrowed", nullable = false, length = 10)
	public Date getDateBorrowed() {
		return this.dateBorrowed;
	}

	public void setDateBorrowed(Date dateBorrowed) {
		this.dateBorrowed = dateBorrowed;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateReturned", length = 10)
	public Date getDateReturned() {
		return this.dateReturned;
	}

	public void setDateReturned(Date dateReturned) {
		this.dateReturned = dateReturned;
	}

}
